### ISSUE TITLE
Would it be possible to create a pip installation?

### ISSUE THREAD

**Issue by LastedApple3** [SpockBotMC/RikerBot#17]
Though the instructions in the docs could be quite useful, it would be simpler if there was a pip installation.
I do not have the capability to run the setup described in the docs, and I'm sure others don't either, so if it were pre-setup, and all you have to do is run the pip install, it would increase the availability.

**Comment by nickelpro** [comment]
Unfortunately while Python is prominent in RikerBot, it's really a C++ project as far as build process goes. While it is possible to teach `pip` to build the project, very little would be gained in simplicity because it would simply be running the required `cmake` command for you. None of the build requirements would change and if your system isn't set up to use the existing build process `pip` would fail too. For now, I think _requiring_ users to invoke `cmake` specifically signposts these requirements.

Eventually it may be possible to upload a binary wheel to PyPI for Windows, so that Windows users could side-step this process. That would require a working Windows build, which would require fixing https://github.com/SpockBotMC/RikerBot/issues/10. Getting CI working on Windows to produce the binaries is non-trivial and not really in my skillset, I did try for a couple hours one weekend, if anyone is a Github actions wizard and can get that process working I would certainly appreciate it and would happily start doing PyPI uploads.

**Comment by nickelpro** [comment]
This is fixed, `pip` can now run `cmake` and build RikerBot. Note that _none of the build requirements have changed_, you can just build the project via invoking pip instead of cmake if you want.
