### ISSUE TITLE
ModuleNotFoundError: No module named 'rikerbot.proto.MinecraftProtocol'

### ISSUE THREAD

**Issue by arthuro555** [SpockBotMC/RikerBot#4]
![image](https://user-images.githubusercontent.com/19349038/90027968-69c80c80-dcb9-11ea-920d-562b1132d489.png)

The installation was abnormally fast but seem to have worked without any error: 
![image](https://user-images.githubusercontent.com/19349038/90028089-8ebc7f80-dcb9-11ea-9c33-94192cde98ca.png)

Platform: Windows 10
Python version: 3.8

**Comment by nickelpro** [comment]
I really need to add something to the setup.py that you can't install it directly. You need to compile the project with cmake first. This is my fault for communicating that poorly and not having install instructions. I'll fix this and document the build system more clearly

**Comment by arthuro555** [comment]
In general this project lacks a bit of documentation in general :/ Wouldn't it be possible to tell pip in setup.py to compile? I thought there were such options (used by numpy for example)

**Comment by nickelpro** [comment]
This project is less than a week old lol, only got through the login process two days ago, and that setup.py was written yesterday. Documentation is a huge priority I promise, making the dev experience work most-goodly does matter to me, even at this early stage.

The build issue is one that was already on my radar though, I know the current path is bad (https://github.com/SpockBotMC/RikerBot/issues/1), and for Windows what really needs to happen is we need Appveyor to be pushing binary builds to PyPI. Getting all the requirements together to build this on Windows is non-trivial for a lot of people. Unfortunately I have very little experience with CI systems so that's going to be a new learning experience for me.
